INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (14, null, 10, 'CF', 'CURRENCY_FINANCING_KEY', '0000000192');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (15, null, 10, 'CFD', 'CURRENCY_FINANCING_DATA_KEY', '0000000624');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (22, null, 8, 'R', 'CLAIM_KEY', '00000105');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (9, null, 10, 'RQ', 'REQUESTER_KEY', '0000000284');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (10, null, 10, 'PR', 'PROPERTY_REQUEST_KEY', '0000000151');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (11, null, 10, 'PD', 'PROPERTY_DESCRIPTION_KEY', '0000000048');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (8, null, 10, 'MC', 'MAIN_CONTRACTUAL_TERMS_KEY', '0000000090');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (1, null, 8, 'BQ', 'USER_KEY', '00000136');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (2, null, 8, 'AT', 'ATTACHMENT_KEY', '00001093');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (3, null, 10, 'DI', 'DIRECT_INVEST_REQUEST_KEY', '0000000910');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (4, null, 10, 'II', 'INVEST_IDENTIFICATION_KEY', '0000000440');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (5, null, 10, 'AS', 'ACTIVITY_SUPPORT_KEY', '0000000719');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (6, null, 10, 'AD', 'ACTIVITY_DECLARATION_KEY', '0000001323');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (7, null, 10, 'PI', 'PARTICIPATION_IDENTIFICATION_KEY', '0000000204');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (12, null, 8, 'INV', 'INVESTOR_KEY', '00000174');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (13, null, 8, 'REP', 'REPRESENTATIVE_KEY', '00000027');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (16, null, 10, 'AR', 'AUTHORISATION_REQUIRED_KEY', '0000000017');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (17, null, 10, 'WR', 'WALLET_REQUEST_KEY', '0000000005');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (18, null, 10, 'SECACQ', 'SECURITIES_ACQUIRED_KEY', '0000000003');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (19, null, 10, 'SECACQDATA', 'SECURITIES_ACQUIRED_DATA_KEY', '0000000010');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (20, null, 10, 'SECACC', 'SECURITIES_ACCOUNT_KEY', '0000000003');
INSERT INTO PI008T_KEY_GEN (PI008_ID, PI008_CRETERIA, PI008_DIGITS, PI008_PREFIX, PI008_TYPE, PI008_VALUE) VALUES (21, null, 10, 'SECACCDATA', 'SECURITIES_ACCOUNT_DATA_KEY', '0000000010');



INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (1, 'Dossier juridique de la société objet de l’investissement ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Dossier juridique de la société objet de l’investissement_AN', 'COMPANY_CREATION');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (2, 'Justificatifs de résidence à l’étranger de l’investisseur', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs de résidence à l’étranger de l’investisseur_AN', 'COMPANY_CREATION');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (3, 'Justificatifs du financement en devise de la participation non-résidente ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs du financement en devise de la participation non-résidente_AN', 'COMPANY_CREATION');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (4, 'Dossier juridique de la société objet de l’investissement ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Dossier juridique de la société objet de l’investissement_AN', 'CAPITAL_INCREASE');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (5, 'Justificatifs de résidence à l’étranger de l’investisseur', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs de résidence à l’étranger de l’investisseur_AN', 'CAPITAL_INCREASE');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (6, 'Justificatifs du financement en devise de la participation non-résidente ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs du financement en devise de la participation non-résidente_AN', 'CAPITAL_INCREASE');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (7, 'Dossier juridique de la société objet de l’investissement ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Dossier juridique de la société objet de l’investissement_AN', 'ACQUISITION_SHARES');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (8, 'Justificatifs de résidence à l’étranger de l’investisseur', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs de résidence à l’étranger de l’investisseur_AN', 'ACQUISITION_SHARES');
INSERT INTO PI016T_SECTION (PI016_ID, PI016_LABEL, PI016_DECLARATION_NATURE, PI016_INVESTMENT_TYPE, PI016_LABEL_AN, PI016_OPERATION_TYPE) VALUES (9, 'Justificatifs du financement en devise de la participation non-résidente ', 'INVESTMENT_FORM', 'DIRECT_INVESTMENT', 'Justificatifs du financement en devise de la participation non-résidente_AN', 'ACQUISITION_SHARES');



INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (1, 'Statuts, dûment enregistrés à la recette des finances ', 'Statuts, dûment enregistrés à la recette des finances ', 'Statuts, dûment enregistrés à la recette des finances ', 'Statuts, dûment enregistrés à la recette des finances ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (2, 'Carte d’identification fiscale ', 'Carte d’identification fiscale ', 'Carte d’identification fiscale ', 'Carte d’identification fiscale ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (3, 'Support d’activité  ', 'Support d’activité  ', 'Support d’activité  ', 'Support d’activité  ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (4, 'Extrait récent du RNE ', 'Extrait récent du RNE ', 'Extrait récent du RNE ', 'Extrait récent du RNE ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (5, 'Carte SINDA (le cas échéant) ', 'Carte SINDA (le cas échéant) ', 'Carte SINDA (le cas échéant) ', 'Carte SINDA (le cas échéant) ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (6, 'Autres ', 'Autres ', 'Autres ', 'Autres ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (7, 'Copie en entier et en couleur du passeport ou carte de séjour ou consulaire en cours de validité ou certificat de résidence à l’étranger ', 'Copie en entier et en couleur du passeport ou carte de séjour ou consulaire en cours de validité ou certificat de résidence à l’étranger ', 'Copie en entier et en couleur du passeport ou carte de séjour ou consulaire en cours de validité ou certificat de résidence à l’étranger ', 'Copie en entier et en couleur du passeport ou carte de séjour ou consulaire en cours de validité ou certificat de résidence à l’étranger ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (8, 'Justificatifs du financement en devises de la participation non-résidente ', 'Justificatifs du financement en devises de la participation non-résidente ', 'Justificatifs du financement en devises de la participation non-résidente ', 'Justificatifs du financement en devises de la participation non-résidente ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (9, 'Statuts, dûment enregistrés ', 'Statuts, dûment enregistrés ', 'Statuts, dûment enregistrés ', 'Statuts, dûment enregistrés ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (10, 'Extrait du registre du commerce étranger ', 'Extrait du registre du commerce étranger ', 'Extrait du registre du commerce étranger ', 'Extrait du registre du commerce étranger ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (11, 'Pièce ayant servi à l’importation des devises ', 'Pièce ayant servi à l’importation des devises ', 'Pièce ayant servi à l’importation des devises ', 'Pièce ayant servi à l’importation des devises ');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (12, 'Copie du contrat de vente', 'Copie du contrat de vente', 'Copy of the sales contract', 'Copy of the sales contract');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (13, 'Dossier juridique', 'Dossier juridique', 'Legal document', 'Legal document');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (14, 'Copie de l''autorisation de la BCT', 'Copie de l''autorisation de la BCT', 'Copy of the authorization from the BCT', 'Copy of the authorization from the BCT');
INSERT INTO PI017T_DOCUMENT (PI017_ID, PI017_DESCRIPTION, PI017_LABEL, PI017_DESCRIPTION_AN, PI017_LABEL_AN) VALUES (15, 'Copie de l''autorisation du gouverneur', 'Copie de l''autorisation du gouverneur', 'Copy of the governor''s authorization', 'Copy of the governor''s authorization');



INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 1, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 1, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 1, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 1, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 1, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 1, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (7, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 2, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 2, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 4, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 4, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 4, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 4, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 4, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 4, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (7, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (8, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (10, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (9, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 5, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 5, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 5, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (11, 6, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 6, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 7, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 7, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 7, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 7, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 7, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 7, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (7, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (8, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (10, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (9, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (1, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (2, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (3, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (4, 8, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (5, 8, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 8, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (11, 9, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 9, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (9, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (10, 2, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (11, 3, 1, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (6, 3, 0, 1);
INSERT INTO PI018_SECTION_DOCUMENT (PI018_DOCUMENT_IDFK, PI018_SECTION_IDFK, PI018_IS_MANDATORY, PI018_REQUESTED_NUMBER) VALUES (8, 2, 1, 1);



INSERT INTO PI023T_IDENTIFICATION_TYPE (PI023_ID, PI023_IS_ACTIVE, PI023_PATTERN, PI023_PROFILE, PI023_TYPE, PI023_PLACEHOLDER) VALUES (1, 1, '^\d{8}$', 'PP;CITIZEN', 'CIN', '12345678');
INSERT INTO PI023T_IDENTIFICATION_TYPE (PI023_ID, PI023_IS_ACTIVE, PI023_PATTERN, PI023_PROFILE, PI023_TYPE, PI023_PLACEHOLDER) VALUES (2, 1, '^[a-zA-Z0-9]{15}$', 'PP;CITIZEN', 'PASSPORT', 'AbC123xyz789456');
INSERT INTO PI023T_IDENTIFICATION_TYPE (PI023_ID, PI023_IS_ACTIVE, PI023_PATTERN, PI023_PROFILE, PI023_TYPE, PI023_PLACEHOLDER) VALUES (6, 1, '^\d{7}[A-Z]{1}$', 'PM', 'IDENTIFIANT UNIQUE', '1234567X');
INSERT INTO PI023T_IDENTIFICATION_TYPE (PI023_ID, PI023_IS_ACTIVE, PI023_PATTERN, PI023_PROFILE, PI023_TYPE, PI023_PLACEHOLDER) VALUES (3, 1, '^\d{7}[A-Z]{1}$', 'PP', 'CARTE SEJOUR', '9876543Y');


INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (1, 'LEGAL_FORM', 'LEGAL_FORM');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (2, 'AUTHORITY', 'AUTHORITY');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (3, 'ACTIVITY_SUPPORT_TYPE', 'ACTIVITY_SUPPORT_TYPE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (4, 'ACTIVITY_CLASS', 'ACTIVITY_CLASS');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (5, 'ACTIVITY_GROUP', 'ACTIVITY_GROUP');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (6, 'ACTIVITY_SECTOR', 'ACTIVITY_SECTOR');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (7, 'ACTIVITY_SUB_SECTOR', 'ACTIVITY_SUB_SECTOR');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (8, 'FINANCIAL_MODE', 'FINANCIAL_MODE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (9, 'DOCUMENT_IMPORT_CURRENCY', 'DOCUMENT IMPORT CURRENCY');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (10, 'LEGAL_FORM_ACTIVITY', 'LEGAL_FORM_ACTIVITY');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (11, 'INVESTMENT_TYPE', 'INVESTMENT_TYPE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (12, 'GROUND_VOCATION', 'GROUND_VOCATION');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (13, 'GROUND_LOCATION', 'GROUND_LOCATION');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (14, 'GROUND_USAGE', 'GROUND_USAGE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (15, 'FINANCIAL_MODE', 'FINANCIAL_MODE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (16, 'IMPORTATION_PIECE', 'IMPORTATION_PIECE');
INSERT INTO PI027_CATEGORY_SPECIFIC_REFERENTIAL (PI027_ID, PI027_CODE, PI027_LABEL) VALUES (17, 'ACCOUNT_MANAGER_TYPE', 'ACCOUNT_MANAGER_TYPE');



INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (1, 'SA', 'Société Anonyme', 'Société Anonyme', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (2, 'SARL', 'Société à responsabilité limitée', 'société à responsabilité limitée', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (3, 'SUARL', 'SUARL', 'SUARL', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (4, 'Société en commandie par actions', 'Société en commandie par actions', 'Société en commandie par actions', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (5, 'EURL', 'Entreprise unipersonnelle à responsabilité limité', 'Entreprise unipersonnelle à responsabilité limité', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (7, 'SNC', 'Société en nom collectif', 'Société en nom collectif', 1, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (8, 'Agence de Promotion de l''Industrie et de l''Innovation (APII)', ' Agence de Promotion de l''Industrie et de l''Innovation (APII)', ' Agence de Promotion de l''Industrie et de l''Innovation (APII)', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (9, 'Agence de Promotion des Investissements Agricoles (APIA)', 'Agence de Promotion des Investissements Agricoles (APIA)', 'Agence de Promotion des Investissements Agricoles (APIA)', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (10, 'Ministère de la Technologie oOffice National de l''Artisanat (ONA)u de l''Innovation', 'Ministère de laOffice National de l''Artisanat (ONA) Technologie ou de l''Innovation', 'Ministère de la Office National de l''Artisanat (ONA)Technologie ou de l''Innovation', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (11, 'Office National du Tourisme Tunisien (ONTT) ', 'Office National du Tourisme Tunisien (ONTT) ', 'Office National du Tourisme Tunisien (ONTT) ', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (12, 'Centre de Promotion des Exportations (CEPEX)', 'Centre de Promotion des Exportations (CEPEX)', 'Centre de Promotion des Exportations (CEPEX)', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (13, 'Parcs d''activités économiques', 'Parcs d''activités économiques', 'Parcs d''activités économiques', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (14, 'Instance Tunisienne d''Investissement (TIA)', 'Instance Tunisienne d''Investissement (TIA)', 'Instance Tunisienne d''Investissement (TIA)', 2, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (15, 'Attestation de dépot de déclaration', 'Attestation de dépot de déclaration', 'Attestation de dépot de déclaration', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (16, 'Cahier des charges', 'Cahier des charges', 'Cahier des charges', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (17, 'Agrément', 'Agrément', 'Agrément
', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (18, 'Toute autre autorisation délivrée par les Autorités compétentes', 'Toute autre autorisation délivrée par les Autorités compétentes', 'Toute autre autorisation délivrée par les Autorités compétentes', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (19, 'Conversion entre l''Etat Tunisien et un Investisseur', 'Conversion entre l''Etat Tunisien et un Investisseur', 'Conversion entre l''Etat Tunisien et un Investisseur', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (20, 'Autorisation de la Banque Centrale de la Tunisie', 'Autorisation de la Banque Centrale de la Tunisie', 'Autorisation de la Banque Centrale de la Tunisie', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (21, 'Carte de commerçant', 'Carte de commerçant', 'Carte de commerçant', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (22, 'Services de Gestion de Patrimoine', 'Services de Gestion de Patrimoine', 'Services de Gestion de Patrimoine', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (24, 'Prêt Hypothécaire', 'Prêt Hypothécaire', 'Prêt Hypothécaire', 3, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (26, 'Banque de détail', 'Banque de détail', 'Banque de détail', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (35, 'Banque d''investissement', 'Banque d''investissement', 'Banque d''investissement', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (27, 'Assurance vie', 'Assurance vie', 'Assurance vie', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (28, 'Assurance automobile', 'Assurance automobile', 'Assurance automobile', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (29, 'Développement logiciel', 'Développement logiciel', 'Développement logiciel', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (30, 'Réseaux et télécommunications', 'Réseaux et télécommunications', 'Réseaux et télécommunications', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (31, 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (32, 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (33, 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (34, 'Gestion d''actifs', 'Gestion d''actifs', 'Gestion d''actifs', 4, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (36, 'Banque de détail', 'Banque de détail', 'Banque de détail', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (37, 'Banque d''investissement', 'Banque d''investissement', 'Banque d''investissement', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (38, 'Assurance vie', 'Assurance vie', 'Assurance vie', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (39, 'Assurance automobile', 'Assurance automobile', 'Assurance automobile', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (40, 'Développement logiciel', 'Développement logiciel', 'Développement logiciel', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (41, 'Réseaux et télécommunications', 'Réseaux et télécommunications', 'Réseaux et télécommunications', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (42, 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (43, 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (44, 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (45, 'Gestion d''actifs', 'Gestion d''actifs', 'Gestion d''actifs', 5, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (46, 'Agroalimentaire', 'Agroalimentaire', 'Agroalimentaire', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (47, 'Banque / Assurance', 'Banque / Assurance', 'Banque / Assurance', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (48, 'Informatique / Télécoms', 'Informatique / Télécoms', 'Informatique / Télécoms', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (49, 'Chimie / Parachimie', 'Chimie / Parachimie', 'Chimie / Parachimie', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (50, 'Transports / Logistique', 'Transports / Logistique', 'Transports / Logistique', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (51, 'Industrie pharmaceutique', 'Industrie pharmaceutique', 'Industrie pharmaceutique', 6, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (52, 'Banque de détail', 'Banque de détail', 'Banque de détail', 7, 47);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (53, 'Banque d''investissement', 'Banque d''investissement', 'Banque d''investissement', 7, 47);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (54, 'Assurance vie', 'Assurance vie', 'Assurance vie', 7, 47);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (55, 'Assurance automobile', 'Assurance automobile', 'Assurance automobile', 7, 47);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (57, 'Développement logiciel', 'Développement logiciel', 'Développement logiciel', 7, 48);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (58, 'Réseaux et télécommunications', 'Réseaux et télécommunications', 'Réseaux et télécommunications', 7, 48);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (59, 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 'Intelligence artificielle et apprentissage automatique', 7, 48);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (60, 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 'Recherche et développement (R and D)', 7, 51);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (61, 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 'Fabrication de produits pharmaceutiques génériques', 7, 51);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (62, 'Gestion d''actifs', 'Gestion d''actifs', 'Gestion d''actifs', 7, 47);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (63, 'Virement de l’étranger', 'Virement de l’étranger', 'Virement de l’étranger', 8, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (64, 'Débit d’un compte étranger', 'Débit d’un compte étranger', 'Débit d’un compte étranger', 8, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (65, 'Billets de banques étrangers ', 'Billets de banques étrangers ', 'Billets de banques étrangers ', 8, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (66, 'Autorisation de la BCT par F2', 'Autorisation de la BCT par F2', 'Autorisation de la BCT par F2', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (67, 'Autorisation de la BCT par lettre ', 'Autorisation de la BCT par lettre ', 'Autorisation de la BCT par lettre ', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (68, 'Fiche d’INVT 93-05 ', 'Fiche d’INVT 93-05 ', 'Fiche d’INVT 93-05 ', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (69, 'Attestation bancaire explicite', 'Attestation bancaire explicite', 'Attestation bancaire explicite', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (70, 'Message Swift ', 'Message Swift ', 'Message Swift ', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (71, 'Avis de débit d’un CE', 'Avis de débit d’un CE', 'Avis de débit d’un CE', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (72, 'Avis de crédit du compte de la société ou du compte du cédant', 'Avis de crédit du compte de la société ou du compte du cédant', 'Avis de crédit du compte de la société ou du compte du cédant', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (73, 'Déclaration douanière ', 'Déclaration douanière ', 'Déclaration douanière ', 9, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (74, 'Loi de l’investissement', 'Loi de l’investissement', 'Loi de l’investissement', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (75, 'Code des hydrocarbures', 'Code des hydrocarbures', 'Code des hydrocarbures', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (76, 'Codes miniers ', 'Codes miniers ', 'Codes miniers ', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (81, 'Acquisition d’un terrain', 'Acquisition d’un terrain', 'Acquisition d’un terrain', 11, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (82, 'Acquisition d’un local bâti', 'Acquisition d’un local bâti', 'Acquisition d’un local bâti', 11, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (83, 'Agricole', 'Agricole', 'Agricole', 12, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (84, 'Non Agricole', 'Non Agricole', 'Non Agricole', 12, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (85, 'Zone industrielle', 'Zone industrielle', 'Zone industrielle', 13, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (86, 'Zone touristique', 'Zone touristique', 'Zone touristique', 13, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (87, 'Autre Zone', 'Autre Zone', 'Autre Zone', 13, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (88, 'Industriel', 'Industriel', 'Industriel', 14, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (89, 'Touristique', 'Touristique', 'Touristique', 14, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (90, 'Commercial', 'Commercial', 'Commercial', 14, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (91, 'Service Agricole', 'Service Agricole', 'Service Agricole', 14, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (92, 'Habitation', 'Habitation', 'Habitation', 14, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (77, 'Loi régissant l’activité du commerce international', 'Loi régissant l’activité du commerce international', 'Loi régissant l’activité du commerce international', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (78, 'Loi relative aux établissements de santé', 'Loi relative aux établissements de santé', 'Loi relative aux établissements de santé', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (79, 'Loi portant promulgation du code de prestations des services financiers aux non-résidents', 'Loi portant promulgation du code de prestations des services financiers aux non-résidents', 'Loi portant promulgation du code de prestations des services financiers aux non-résidents', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (80, 'Convention signée avec l’Etat Tunisien', 'Convention signée avec l’Etat Tunisien', 'Convention signée avec l’Etat Tunisien', 10, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (93, 'Virement de l’étranger', 'Virement de l’étranger', 'Virement de l’étranger', 15, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (94, 'Débit d’un compte étranger', 'Débit d’un compte étranger', 'Débit d’un compte étranger', 15, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (95, 'Billets de banques étrangers  ', 'Billets de banques étrangers  ', 'Billets de banques étrangers  ', 15, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (96, 'Autorisation de la BCT par F2', 'Autorisation de la BCT par F2', 'Autorisation de la BCT par F2', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (97, 'Autorisation de la BCT par lettre', 'Autorisation de la BCT par lettre', 'Autorisation de la BCT par lettre', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (98, 'Fiche d’INVT 93-05', 'Fiche d’INVT 93-05', 'Fiche d’INVT 93-05', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (99, 'Attestation bancaire explicite', 'Attestation bancaire explicite', 'Attestation bancaire explicite', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (100, 'Message Swift', 'Message Swift', 'Message Swift', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (101, 'Avis de débit d’un CE', 'Avis de débit d’un CE', 'Avis de débit d’un CE', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (102, 'Avis de crédit du compte de la société ou du cédant', 'Avis de crédit du compte de la société ou du cédant', 'Avis de crédit du compte de la société ou du cédant', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (103, 'Déclaration douanière', 'Déclaration douanière', 'Déclaration douanière', 16, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (104, 'Intermédiaire en bourse', 'Intermédiaire en bourse', 'Intermédiaire en bourse', 17, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (105, 'Banque', 'Banque', 'Banque', 17, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (106, 'Société de gestion', 'Société de gestion', 'Société de gestion', 17, null);
INSERT INTO PI026_SPECIFIC_REFERENTIAL (PI026_ID, PI026_CODE, PI026_DESCRIPTION, PI026_LABEL, PI026_CATEGORY_SPECIFIC_REFERENTIAL_ID, PI026_PARENT_ID) VALUES (107, 'Société de titrisation', 'Société de titrisation', 'Société de titrisation', 17, null);


INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (2, TIMESTAMP '2023-12-25 10:24:29.000000', 'codification.address', null, '^[A-Z0-9 ]{0,60}$');
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (3, TIMESTAMP '2023-12-25 10:31:03.000000', 'codification.socialReason', null, '^[^€]{0,90}$');
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (1, TIMESTAMP '2023-12-19 22:04:13.393000', 'path.attachment.repo', '/data/', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (5, TIMESTAMP '2023-12-25 14:31:03.000000', 'country.code.tn', 'TN', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (6, TIMESTAMP '2023-12-25 14:48:03.000000', 'legal.form.sa', 'SA', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (8, TIMESTAMP '2024-01-03 13:22:29.000000', 'referenciel.piece', '68', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (9, TIMESTAMP '2024-01-08 11:43:24.000000', 'referenciel.reserve', '66', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (4, TIMESTAMP '2023-12-25 11:31:03.000000', 'path.reporting', '/data/pi/investment/templates', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (10, TIMESTAMP '2024-01-08 14:04:19.000000', 'GROUND_USAGE', '92,', 'GROUND_LOCATION');
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (11, TIMESTAMP '2024-01-08 15:04:46.000000', 'referential.vocation', '12', '83,');
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (12, TIMESTAMP '2024-01-08 16:28:49.000000', 'file.size.limit', '2', null);
INSERT INTO PI030T_PARAMETER (PI030_ID, PI030_CREATION_DATE, PI030_PARAMETER_KEY, PI030_PARAMETER_VALUE, PI030_PARAMETER_PATTERN) VALUES (7, TIMESTAMP '2024-01-03 09:40:09.000000', 'activitySupport.declarationCertificateOfDeposit', '15,', null);

Insert into PI001T_ACCOUNT (PI001_ID,PI001_CELL_PHONE,PI001_CREATION_DATETIME,PI001_EXPIRATION_DATE,PI001_FIRST_NAME,PI001_IS_ACTIVE,PI001_IS_FIRST_CONNECTION,PI001_USER_LANGUAGE,PI001_LAST_NAME,PI001_LOGIN,PI001_MODIFICATON_DATETIME,PI001_PASSWORD,PI001_PASSWORD_MODIFICATON_DATE,PI001_USER_TYPE,PI001_CREATED_BY,PI001_MODIFIED_BY) values ('BQ202300000001',null,to_timestamp('22-11-23 20:09:06.506000000','DD-MM-RR HH24:MI:SSXFF'),null,'Khouni',1,1,'FR','Amira','amira.khouni@bct.gov.tn',null,'$2a$12$d9dc.yChw./Cs/NzkqoQZumeI1AODr6pxRNg/hKBHaMFRiqaxfq9m',null,'BCT_ADMIN',null,null);
Insert into PI004T_BCT_AGENT (PI004_GENERAL_MANAGEMENT_ASSIGNMENT,PI004_IS_ADMIN,PI004_REGISTRATION_NUMBER,PI004_SERVICE_ASSIGNMENT,PI001_ID) values ('generalManagementAssignment',1,'123456987','serviceAssignment','BQ202300000001');

COMMIT;

DECLARE
  content1 CLOB;
  content2 CLOB;
  content3 CLOB;
BEGIN
	
	content1 := '[
    {
      "dataIndex": "reference",
      "sortIndex": "id",
      "label": {
        "en": "Reference",
        "fr": "Réference"
      }
    },
   
    {
      "dataIndex": "formInvest",
      "sortIndex": "operationType",
      "label": {
        "en": "Operation Type",
        "fr": "Type Opération"
      }
    },
    {
      "dataIndex": "companyName",
      "sortIndex": "investIdentification.companyName",
      "label": {
        "en": "Company Name",
        "fr": "Nom Société "
      }
    },
    {
      "dataIndex": "companyIdentifier",
      "sortIndex": "investIdentification.uniqueIdentifier",
      "label": {
        "en": "Unique identifier",
        "fr": "Identifiant Unique"
      }
    },
    {
      "dataIndex": "bank",
      "sortIndex": "bank.code",
      "label": {
        "en": "Bank",
        "fr": "Banque"
      }
    }
,
    {
      "dataIndex": "status",
      "sortIndex": "status",
      "label": {
        "en": "Status",
        "fr": "Statut"
      }
    }
  ]';
  
  content2 := '[
    {
      "dataIndex": "reference",
      "sortIndex": "id",
      "label": {
        "en": "Reference",
        "fr": "Réference"
      }
    },
    {
      "dataIndex": "investorName",
      "sortIndex": "invistor.socialReason,invistor.firstName,invistor.lastName",
      "label": {
        "en": "Investor",
        "fr": "Investisseur"
      }
    },
    {
      "dataIndex": "formInvest",
      "sortIndex": "operationType",
      "label": {
        "en": "Operation Type",
        "fr": "Type Opération"
      }
    },
    {
      "dataIndex": "companyName",
      "sortIndex": "investIdentification.companyName",
      "label": {
        "en": "Company Name",
        "fr": "Nom Société "
      }
    },
    {
      "dataIndex": "companyIdentifier",
      "sortIndex": "investIdentification.uniqueIdentifier",
      "label": {
        "en": "Unique identifier",
        "fr": "Identifiant Unique"
      }
    },
    {
      "dataIndex": "bank",
      "sortIndex": "bank.code",
      "label": {
        "en": "Bank",
        "fr": "Banque"
      }
    }
,
    {
      "dataIndex": "status",
      "sortIndex": "status",
      "label": {
        "en": "Status",
        "fr": "Statut"
      }
    }
  ]';
  
  content3 := '[
    {
      "dataIndex": "reference",
      "sortIndex": "id",
      "label": {
        "en": "Reference",
        "fr": "Réference"
      }
    },
    {
      "dataIndex": "investorName",
      "sortIndex": "invistor.socialReason",
      "label": {
        "en": "Investor",
        "fr": "Investisseur"
      }
    },
    {
      "dataIndex": "formInvest",
      "sortIndex": "operationType",
      "label": {
        "en": "Operation Type",
        "fr": "Type Opération"
      }
    },
    {
      "dataIndex": "companyName",
      "sortIndex": "investIdentification.companyName",
      "label": {
        "en": "Company Name",
        "fr": "Nom Société "
      }
    },
    {
      "dataIndex": "companyIdentifier",
      "sortIndex": "investIdentification.uniqueIdentifier",
      "label": {
        "en": "Unique identifier",
        "fr": "Identifiant Unique"
      }
    },
    {
      "dataIndex": "status",
      "sortIndex": "status",
      "label": {
        "en": "Status",
        "fr": "Statut"
      }
    }
  ]';

	
    INSERT INTO PI033T_CONFIGURATION_SEARCH_FIELD (PI033_ID, PI033_CONFIG_DATA, PI033_INVESTMENT_TYPE, PI033_REQUEST_BEAN_NAME, PI033_USER_TYPE) VALUES (1,content1 , 'DIRECT_INVESTMENT', null, 'INVESTOR');
    INSERT INTO PI033T_CONFIGURATION_SEARCH_FIELD (PI033_ID, PI033_CONFIG_DATA, PI033_INVESTMENT_TYPE, PI033_REQUEST_BEAN_NAME, PI033_USER_TYPE) VALUES (2,content2 , 'DIRECT_INVESTMENT', null, 'BCT_AGENT');
	INSERT INTO PI033T_CONFIGURATION_SEARCH_FIELD (PI033_ID, PI033_CONFIG_DATA, PI033_INVESTMENT_TYPE, PI033_REQUEST_BEAN_NAME, PI033_USER_TYPE) VALUES (3, content3, 'DIRECT_INVESTMENT', null, 'BANKER');	
 
 COMMIT;
  
END;
/


DECLARE
  content1 CLOB;
  content2 CLOB;
  content3 CLOB;
  content4 CLOB;
  content5 CLOB;
  content6 CLOB;
  content7 CLOB;
  content8 CLOB;
  content9 CLOB;
  content10 CLOB;
  content11 CLOB;
  content12 CLOB;
  content13 CLOB;
  content14 CLOB;
BEGIN


	content1 := '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Declaration Success</title>
</head>
<body>
    <p>Your declaration has been successfully transmitted to your bank.</p>
    <strong>Your bank reference:</strong> $!{BANKREFERENCE}<br>
    <strong>Declaration date:</strong> $!{DECLARATIONDATE}<br>
    <img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</body>
</html>';
	content2 := '<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Succès de la déclaration</title>
</head>
<body>
    <p>Votre déclaration a été transmise avec succès à votre banque.</p>
    <strong>Référence de votre banque :</strong> $!{BANKREFERENCE}<br>
    <strong>Date de déclaration :</strong> $!{DECLARATIONDATE}<br>
    <img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</body>
</html>';
	content3 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Contact Form Submission</title>
</head>
<body>
#set($containerStyle = "width: 100%; max-width: 1000px; margin: 20px auto; padding: 20px; box-sizing: border-box; border: 1px solid #CCCCCC; border-radius: 8px;")
<div class="container" style="$containerStyle">

    #set($contentStyle = "width: 100%;")

    <div style="$contentStyle">
        <label>Hello, </label><br>
        <label>By this notice, we inform you that a bank account has been created in your name on the platform for foreign currency investments in Tunisia.</label><br>
        <label>To access it, we invite you to enter the following details:</label><br>
        <label>Login:</label>
        <input disabled type="text" id="label5" name="label4" value="${!LOGIN}" placeholder=""><br>
        <label>Password:</label>
        <input disabled type="text" id="label6" name="label4" value="${!PSWD}" placeholder=""><br><br><br>
        <label>Please note that you will need to reset your password after the first login.<br><br>Best regards</label>
    </div>    <img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">

</div>
</body>
</html>';
	content4 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Soumission de formulaire de contact</title>
</head>
<body>
#set($containerStyle = "width: 100%; max-width: 1000px; margin: 20px auto; padding: 20px; box-sizing: border-box; border: 1px solid #CCCCCC; border-radius: 8px;")

<div class="container" style="$containerStyle">

    #set($contentStyle = "width: 100%;")

    <div style="$contentStyle">
        <label>Bonjour, </label><br>
        <label>Par le présent, nous vous informons que un compte banquier a été créé en votre nom sur la plateforme des investissements en devises des non-résidents en Tunisie.</label><br>
        <label>Pour y accéder, nous vous invitons à saisir les coordonnées suivantes :</label><br>
        <label>Login:</label>
        <input disabled type="text" id="label5" name="label4" value="$!{LOGIN}" placeholder=""><br>
        <label>Mot de Passe:</label>
        <input disabled type="text" id="label6" name="label4" value="$!{PSWD}" placeholder=""><br><br><br>
        <label>Il convient de vous signaler que vous devrez réinitialiser votre mot de passe suite à la première connexion.<br><br>Cordialement</label>
    </div>
<img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';
	content5 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Creation of Bank Administrator Account</title>
</head>
<body>
<div class="container">
    <div class="input-group">
        <label for="label1">Authorized Intermediary:</label>
        <input disabled type="text" id="label1" name="label1" value="$!{INTERMIDIAIRE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label2">Administrator Type:</label>
        <input disabled type="text" id="label2" name="label2" value="$!{ADMINTYPE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label3">Banker System ID:</label>
        <input disabled type="text" id="label3" name="label3" value="$!{ID}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label4">Name and Surname:</label>
        <input disabled type="text" id="label4" name="label4" value="$!{NOM}" placeholder="">
    </div>

    <div style="width: 100%">
        <label>Hello, </label><br>
        <label>By this notice, we inform you that a Bank Administrator account has been created in your name on the platform for foreign currency investments for non-residents in Tunisia.</label><br>
        <label>To access it, we invite you to enter the following details:</label><br>
        <label>Login:</label>
        <input disabled type="text" id="label5" name="label4" value="$!{LOGIN}" placeholder=""><br>
        <label>Password:</label>
        <input disabled type="text" id="label6" name="label4" value="$!{PSWD}" placeholder=""><br><br><br>
        <label>Please be advised that you will need to reset your password after the first login.<br><br>Best regards</label>
    </div>
</div>
</body>
</html>';
	content6 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Création de compte Administrateur Banque</title>
</head>
<body>
<div class="container">
    <div class="input-group">
        <label for="label1">Intermédiaire Agréé :</label>
        <input disabled type="text" id="label1" name="label1" value="$!{INTERMIDIAIRE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label2">Type de administrateur :</label>
        <input disabled type="text" id="label2" name="label2" value="$!{ADMINTYPE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label3">ID-Système du banquier :</label>
        <input disabled type="text" id="label3" name="label3" value="$!{ID}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label4">Nom et prénom :</label>
        <input disabled type="text" id="label4" name="label4" value="$!{NOM}" placeholder="">
    </div>

    <div style="width: 100%">
        <label>Bonjour, </label><br>
        <label>Par le présent, nous vous informons que un compte Administrateur banque a été créé en votre nom sur la plateforme des investissements en devises des non-résidents en Tunisie.</label><br>
        <label>Pour y accéder, nous vous invitons à saisir les coordonnées suivantes :</label><br>
        <label>Login :</label>
        <input disabled type="text" id="label5" name="label4" value="$!{LOGIN}" placeholder=""><br>
        <label>Mot de Passe :</label>
        <input disabled type="text" id="label6" name="label4" value="$!{PSWD}" placeholder=""><br><br><br>
        <label>Il convient de vous signaler que vous devrez réinitialiser votre mot de passe suite à la première connexion.<br><br>Cordialement</label>
    </div><img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';
	content7 := '<!DOCTYPE html>
<html>
<head>
    <style>
    

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Contact Form Submission</title>
</head>
<body>
#set($containerStyle = "width: 80%; max-width: 1000px; margin: 20px auto; padding: 20px; box-sizing: border-box; border: 1px solid #CCCCCC; border-radius: 8px;")
<div class="container" style="$containerStyle">

    <div class="input-group">
        <label for="label1">General Direction:</label>
        <input disabled type="text" id="label1" name="label1" value="$!{GENERALDIRECTION}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label2">Service:</label>
        <input disabled type="text" id="label2" name="label2" value="$!{SERVICE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label3">Banker System ID:</label>
        <input disabled type="text" id="label3" name="label3" value="$!{ID}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label4">Name and Surname:</label>
        <input disabled type="text" id="label4" name="label4" value="$!{FIRSTNAME}" placeholder="">
    </div>

    <div style="width: 100%">
        <label>Hello, </label><br>
        <label>By this notice, we inform you that a BCT consultant account has been created in your name on the platform for foreign currency investments for non-residents in Tunisia.</label><br>
        <label>To access it, we invite you to enter the following details:</label><br>
        <label>Login:</label>
        <input disabled type="text" id="label5" name="label4" value="$!{LOGIN}" placeholder=""><br>
        <label>Password:</label>
        <input disabled type="text" id="label6" name="label4" value="$!{PSWD}" placeholder=""><br><br><br>
        <label>Please be advised that you will need to reset your password after the first login.<br><br>Best regards</label>
    </div>    <img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">

</div>
</body>
</html>';
	content8 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .input-group {
            margin-bottom: 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        label {
            font-size: 14px;
            color: #1E2538;
            align-self: center;
        }

        input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #CACEDB;
            border-radius: 4px;
            margin-top: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #E6E8F0;
            border-radius: 4px;
            margin-top: 5px;
            resize: vertical;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Création de compte Consultant BCT</title>
</head>
<body>
#set($containerStyle = "width: 80%; max-width: 1000px; margin: 20px auto; padding: 20px; box-sizing: border-box; border: 1px solid #CCCCCC; border-radius: 8px;")
<div class="container" style="$containerStyle">

    <div class="input-group">
        <label for="label1">Direction Générale :</label>
        <input disabled type="text" id="label1" name="label1" value="$!{GENERALDIRECTION}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label2">Service :</label>
        <input disabled type="text" id="label2" name="label2" value="$!{SERVICE}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label3">ID du Système Bancaire :</label>
        <input disabled type="text" id="label3" name="label3" value="$!{ID}" placeholder="">
    </div>

    <div class="input-group">
        <label for="label4">Nom et Prénom :</label>
        <input disabled type="text" id="label4" name="label4" value="$!{FIRSTNAME}" placeholder="">
    </div>

    <div style="width: 100%">
        <label>Bonjour, </label><br>
        <label>Par la présente, nous vous informons que un compte Consultant BCT a été créé en votre nom sur la plateforme investissements en devises étrangères pour les non-résidents en Tunisie.</label><br>
        <label>Pour y accéder, nous vous invitons à saisir les détails suivants :</label><br>
        <label>Login :</label>
        <input disabled type="text" id="label5" name="label4" value="$!{LOGIN}" placeholder=""><br>
        <label>Mot de Passe :</label>
        <input disabled type="text" id="label6" name="label4" value="$!{PSWD}" placeholder=""><br><br><br>
        <label>Veuillez noter que vous devrez réinitialiser votre mot de passe après la première connexion.<br><br>Cordialement</label>
    </div><img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';
	content9 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .message {
            font-size: 16px;
            color: #1E2538;
            margin-bottom: 20px;
        }

        .reset-link {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Password Reset</title>
</head>
<body>
<div class="container">
    <div class="message">
        To reset your password, please click the link below:
    </div>

    <a class="reset-link" href="${URL}?key=$!{KEY}">Reset Password</a>

</div>
</body>
</html>';
	content10 := '<!DOCTYPE html>
<html>
<head>
    <style>


        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .message {
            font-size: 16px;
            color: #1E2538;
            margin-bottom: 20px;
        }

        .reset-link {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Réinitialisation de mot de passe </title>
</head>
<body>
<div class="container">
    <div class="message">
        Pour réinitialiser votre mot de passe, veuillez cliquer sur le lien ci-dessous :
    </div>
    <a class="reset-link" href="${URL}?key=${KEY}">Reset Password</a>
<img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';
	content11 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .message {
            font-size: 16px;
            color: #1E2538;
            margin-bottom: 20px;
        }

        .activation-link {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Account Activation</title>
</head>
<body>
<div class="container">
    <div class="message">
        To complete your registration, please click the link below to activate your account:
    </div>

    <a class="activation-link" href="$!{ACCOUNTACTIVATIONURL}?key=$!{ACTIVATIONKEY}">Activate Account</a>

    <br><br>
    <div>
        ID: $!{ID} <br>
        Email: $!{EMAIL} <br>
        Password: $!{PASSWORD}
    </div>
</div>
</body>
</html>';
	content12 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }

        .message {
            font-size: 16px;
            color: #1E2538;
            margin-bottom: 20px;
        }

        .activation-link {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }
    </style>
    <meta charset="UTF-8"/>
    <title>Activation du compte</title>
</head>
<body>
<div class="container">
    <div class="message">
        Pour finaliser votre inscription, veuillez cliquer sur le lien ci-dessous pour activer votre compte :
    </div>

    <a class="activation-link" href="$!{ACCOUNTACTIVATIONURL}?key=$!{ACTIVATIONKEY}">Activate Account</a>

    <br><br>
    <div>
        ID: $!{ID} <br>
        Email: $!{EMAIL} <br>
        Mot de Passe : $!{PASSWORD}
    </div><img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';
	content13 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }
    </style>
    <meta charset="UTF-8"/>
</head>
<body>
<div class="container">
 <h2 style="color:black"> Hello, <br> <br>
    We hereby inform you that a banker account has been created in your name. <br>
    To activate your account, we invite you to access it using the following credentials: <br>
</h2>
    <br><br>
    <div>
        Email: $!{EMAIL} <br>
        Password: $!{PSWD}
    </div>

<h2> Please be advised that you will need to reset your password after the first login. <br> <br>
    Best regards
</h2>
</div>
</body>
</html>';
	content14 := '<!DOCTYPE html>
<html>
<head>
    <style>

        body {
            font-family: "Inter", sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            box-sizing: border-box;
            border: 1px solid #CCCCCC;
            border-radius: 8px;
        }
    </style>
    <meta charset="UTF-8"/>
</head>
<body>
<div class="container">
 <h2 style="color:black">
Bonjour, <br> <br>
Par la présente, nous vous informons que un compte bancaire a été créé à votre nom. <br>
Pour activer votre compte, nous vous invitons à y accéder en utilisant les identifiants suivants : <br>
</h2>
    <br><br>
    <div>
        Email: $!{EMAIL} <br>
        Mot de Passe : $!{PSWD}
    </div>

<h2>Veuillez noter que vous devrez réinitialiser votre mot de passe après la première connexion. <br> <br>
    Cordialement
</h2><img src="https://www.bct.gov.tn/bct/siteprod/images/logo.png" alt="logo">
</div>
</body>
</html>';


    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES (content1 ,content2, 'Your declaration has been successfully transmitted to your bank.\nBank reference: $bankReference\nDeclaration date: $declarationDate\n', 'Your declaration has been successfully transmitted to your bank.\nBank reference: $bankReference\nDeclaration date: $declarationDate\n', 'TRANSMISSION', 'Folder Transmission', 'Transmission Dossier');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES (content3 ,content4, 'x', 'x', 'ACCOUNT_BANKER', 'Banker Creation', 'Création d''un Banquier');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES ( content5,content6, 'a', 'a', 'ACCOUNT_ADMIN_BANKER', 'Admin Banker Creation', 'Création d''un admin Banquier');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES ( content7,content8, 'w', 'w', 'ACCOUNT_BCT_AGENT', 'BCT Agent Creation', 'Création Agent BCT');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES ( content11,content12 , 'Activate your account', 'Activate your account', 'ACTIVATION_LINK', 'Activate your account PI', 'Activer Votre Compte PI');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES (content9 , content10, 'To reset your password, please click the link below:', 'To reset your password, please click the link below:', 'FORGOT_PASSWORD', 'Password reset request - PI', 'Password reset request - PI');
    INSERT INTO PI031T_EMAIL_TEMPLATE ( PI030T_CONTENT_HTML_EN, PI030T_CONTENT_HTML_FR, PI030T_CONTENT_TEXT_EN, PI030T_CONTENT_TEXT_FR, PI030T_LABEL, PI030T_OBJECT_EN, PI030T_OBJECT_FR) VALUES (content13 ,content14 , 'a', 'a', 'ACCOUNT_CREATED', 'Banker Account Creation', 'Création de compte bancaire');
  
  
  COMMIT;
  
END;
/
