# Generated by Django 4.2.3 on 2025-08-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_size', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=100)),
            ],
        ),
    ]
