# Generated by Django 4.2.3 on 2025-08-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_document_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_url',
            new_name='file',
        ),
    ]
