# Generated by Django 4.2.3 on 2025-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_file_url_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='file_url',
        ),
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
