# Generated by Django 4.2.3 on 2025-08-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_file_document_file_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_url',
            new_name='file',
        ),
    ]
