# Generated by Django 4.2.3 on 2025-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_file_url_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
